site_name: fun-with-flags
theme:
  name: material

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Test concept: test-concept.md
  - Architecture:
      - Introduction and Goals: architecture/01_introduction_and_goals.md
      - Architecture Constraints: architecture/02_architecture_constraints.md
      - Context and Scope: architecture/03_context_and_scope.md
      - Solution Strategy: architecture/04_solution_strategy.md
      - Building Block View: architecture/05_building_block_view.md
      - Runtime View: architecture/06_runtime_view.md
      - Deployment View: architecture/07_deployment_view.md
      - Cross-cutting Concepts: architecture/08_crosscutting_concepts.md
      - Architecture Decisions: architecture/09_architecture_decisions.md
      - Quality Requirements: architecture/10_quality_requirements.md
      - Risks and Technical Debts: architecture/11_risks_and_technical_debts.md
      - Glossary: architecture/12_glossary.md